version: '3'
services:
  cron:
    build: https://github.com/muebau/inwx-ipv6-update.git#:build
    network_mode: "host"  
    environment:
      INWX_USER: "user"
      INWX_PASS: "pass"
      RECORDS: >
        [
          {
            "domain": "domain.tld",
            "record": "domain.tld"
          },
          {
            "domain": "domain2.tld",
            "record": "subdomain.domain2.tld"
          }
        ]
